name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Debug - Check Environment Variables
        run: |
          echo "Checking if environment variables are set (not showing values for security):"
          if [ ! -z "$VITE_API_KEY" ]; then echo "VITE_API_KEY is set"; else echo "VITE_API_KEY is NOT set"; fi
          if [ ! -z "$VITE_AUTH_DOMAIN" ]; then echo "VITE_AUTH_DOMAIN is set"; else echo "VITE_AUTH_DOMAIN is NOT set"; fi
          if [ ! -z "$VITE_PROJECT_ID" ]; then echo "VITE_PROJECT_ID is set"; else echo "VITE_PROJECT_ID is NOT set"; fi
          if [ ! -z "$VITE_STORAGE_BUCKET" ]; then echo "VITE_STORAGE_BUCKET is set"; else echo "VITE_STORAGE_BUCKET is NOT set"; fi
          if [ ! -z "$VITE_MESSAGING_SENDER_ID" ]; then echo "VITE_MESSAGING_SENDER_ID is set"; else echo "VITE_MESSAGING_SENDER_ID is NOT set"; fi
          if [ ! -z "$VITE_APP_ID" ]; then echo "VITE_APP_ID is set"; else echo "VITE_APP_ID is NOT set"; fi
          if [ ! -z "$VITE_MEASUREMENT_ID" ]; then echo "VITE_MEASUREMENT_ID is set"; else echo "VITE_MEASUREMENT_ID is NOT set"; fi
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}

      - name: Build
        env:
          VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
          VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
          VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
          VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
          VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
          VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
          VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
